### ISSUE TITLE
example gradlew rest doesn't work

### ISSUE THREAD

**Issue by aris-vlasakakis-ck** [sheehan/job-dsl-rest-example#1]
running against a local installation with username and password, the gradle tasks completes with no errors, and it doesn't work.

This is to create the seed job from your job-dsl-gradle-examples repository

Example:

```bash
$ ./gradlew rest -Dpattern="jobs/seed.groovy" -DbaseUrl="http://127.0.0.1:8080" -Dusername=admin -Dpassword=admin
:compileJava NO-SOURCE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:rest

BUILD SUCCESSFUL

Total time: 1.552 secs
```

...and nothing happened in the Jenkins installation as well!

**Comment by sheehan** [comment]
Hi @aris-vlasakakis-ck. It should be `-Dpattern="src/jobs/seed.groovy"`
